# Generated by Django 4.2.7 on 2023-11-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_application_applicant_alter_application_pet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='lastupdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
