# Generated by Django 4.2.7 on 2023-11-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_application_lastupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(default='Available', max_length=200),
        ),
    ]
