# Generated by Django 4.2.7 on 2023-12-12 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('frequency', models.CharField(blank=True, choices=[('one_time', 'one_time'), ('monthly', 'monthly'), ('quarterly', 'quarterly'), ('yearly', 'yearly')], default='one_time', max_length=200)),
                ('comment', models.CharField(max_length=1000)),
                ('credit_card', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
    ]
